# Generated by Django 4.0.4 on 2022-07-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('team_and_background', models.TextField(max_length=200)),
                ('comapany_and_products', models.TextField(max_length=200)),
                ('problem', models.TextField(max_length=200)),
                ('about_solution', models.TextField(max_length=200)),
                ('proposition', models.TextField(max_length=200)),
                ('competetors_and_advantages', models.TextField(max_length=200)),
                ('revenue_model', models.TextField(max_length=200)),
                ('market_products_and_service', models.TextField(max_length=200)),
                ('marketing_plan', models.TextField(max_length=200)),
                ('business_proposal', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
