# Generated by Django 4.0.4 on 2022-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_incubation_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='company_logo',
            field=models.ImageField(default=1, upload_to='company_logo'),
            preserve_default=False,
        ),
    ]
