# Generated by Django 4.0.4 on 2022-07-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_incubation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incubation',
            old_name='comapany_and_products',
            new_name='company_and_products',
        ),
    ]
