# Generated by Django 4.0.4 on 2022-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_comapany_and_products_incubation_company_and_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='radio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
