# Generated by Django 4.0.4 on 2022-07-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_incubation_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
    ]
