# Generated by Django 4.0.4 on 2022-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bookingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
