# Generated by Django 4.0.4 on 2022-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_bookingslot_date_bookingslot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=50),
        ),
    ]
